### ISSUE TITLE
Liberal Studies logic incorrect

### ISSUE THREAD

**Issue by abcdefguan** [cornell-dti/course-plan#399]
I (gw284@cornell.edu) have a single liberal studies course, AP Macroeconomics. This is incorrect and I should have 2 liberal studies courses, AP Macroeconomics and AP Microeconomics. But for the sake of this bug, assume that I have 1 liberal study. Liberal Studies says 0 / 6 courses for some reason even though it should be 1 / 6.
![Screenshot from 2021-03-27 14-18-05](https://user-images.githubusercontent.com/9957585/112730334-68c1b380-8f07-11eb-8392-14fcf5db0918.png)

**Comment by SamChou19815** [comment]
Looks like it should be resolved by #411 as well.

**Comment by abcdefguan** [comment]
Issue still not fixed:

AP Microeconomics should be counted as liberal studies
AP Physics C Mechanics should be counted as equivalent of PHYS 1112

**Comment by abcdefguan** [comment]
Sorry that was on the wrong issue. This issue has been fixed, but a related issue has not yet been fixed.
